### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by wengdunfang** [yuange250/video_pedestrian_attributes_recognition#1]
Hi, I am runing your code, there are so many errors. 
such as IndexError: list index out of range 
**_**File "main_video_attr_recog.py", line 227, in attr_main
    attr_train(model, criterion, optimizer, trainloader, use_gpu)
  File "main_video_attr_recog.py", line 268, in attr_train
    loss += criterion(outputs[i], attrs[i]) / attr_lens[i]**_**

**Comment by wengdunfang** [comment]
data_manager.py line:59
self.attributes = pd.read_csv(osp.join(self.root,"mars_attr.csv"))
but , no exit mars_attr.csv. only exit mars_attributes.csv.
can you update it completely.
thanks you.

**Comment by yuange250** [comment]
thanks very much, when i'm too careless to working on these codes since i'm a little busy that time, i/m going to update this codes this night, thanks for your appointment!!!!!

**Comment by wengdunfang** [comment]
> 
> 
> thanks very much, when i'm too careless to working on these codes since i'm a little busy that time, i/m going to update this codes this night, thanks for your appointment!!!!!

Thank you for your prompt reply. I am also a student of Buaa. My weChat:  wengdunfang
