### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by Vivinia** [yuange250/video_pedestrian_attributes_recognition#2]
Hello, I found your code recently and wanted to try it, but I found that in the website provided in the paper, the data set download page could not be accessed. Could you tell me where I can download the data set?

**Comment by yuange250** [comment]
> Hello, I found your code recently and wanted to try it, but I found that in the website provided in the paper, the data set download page could not be accessed. Could you tell me where I can download the data set?

给我邮箱吧～
