### ISSUE TITLE
Problem with dowloading dataset from Europe

### ISSUE THREAD

**Issue by joppichristian** [yuange250/video_pedestrian_attributes_recognition#3]
Hello,
I'm interested in MARS and DUKE datasets with attribute annotations.
However, I cannot register myself on the Baidu website since I haven't any Chinese telephone number. So, I cannot download the annotations.
Could you also share the dataset on GoogleDrive or Dropbox cloud services?

Thanks!

**Comment by yuange250** [comment]
> Hello,
> I'm interested in MARS and DUKE datasets with attribute annotations.
> However, I cannot register myself on the Baidu website since I haven't any Chinese telephone number. So, I cannot download the annotations.
> Could you also share the dataset on GoogleDrive or Dropbox cloud services?
> 
> Thanks!

sorry for this problem, could u please give me your mail address?

**Comment by yuange250** [comment]
> Hello,
> I'm interested in MARS and DUKE datasets with attribute annotations.
> However, I cannot register myself on the Baidu website since I haven't any Chinese telephone number. So, I cannot download the annotations.
> Could you also share the dataset on GoogleDrive or Dropbox cloud services?
> 
> Thanks!

And I just put the files on the google Drive:
https://drive.google.com/drive/folders/1E5rP1CtXstQdGROktUVn7BVSVaVv1qOt?usp=sharing

**Comment by joppichristian** [comment]
Thanks a lot!!
